name: Generate Lists

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  check-if-there-are-commits:
    runs-on: ubuntu-latest
    outputs:
      alive: ${{ steps.check.outputs.alive }}
    steps:
      ### Activity check
      ### uses GitHub API to check last non-automagic commit in repository
      ### if it's older than a week, all other steps are skipped
      - name: Activity check
        id: "check"
        run: |
          curl -sL https://api.github.com/repos/uklans/cache-domains/commits?sha=master | jq -r '.[0]' > $HOME/commit.json
          echo $GITHUB_REPOSITORY
          echo $HOME
          echo $(cat $HOME/commit.json)

          date="$(jq -r '.commit.author.date' $HOME/commit.json)"
          echo "Date: $date"
          timestamp=$(date --utc -d "$date" +%s)
          echo "Timestamp: $timestamp"
          echo "Current date: $(date --utc +%s)"
          echo "Difference between the current date and time of the last commit: $(( ( $(date --utc +%s) - $timestamp ) ))"
          days=$(( ( $(date --utc +%s) - $timestamp ) / 86400 ))
          echo "Days: $days"

          alive=0

          echo "Date: $date"
          echo "timestamp: $timestamp"
          echo "days: $days"

          if [ $days -lt 1 ]; then
            echo Repository active : $days days
            alive=1
          else
            echo "Skipping update since uklans/cache-domains has not been updated."
          fi
          echo "Alive? $alive"
          if [ $alive -eq 1 ]; then
            echo "REPO_ALIVE=true" >> $GITHUB_ENV
            echo "::set-output name=alive::true"
          else
            echo "REPO_ALIVE=false" >> $GITHUB_ENV
            echo "::set-output name=alive::false"
          fi
          echo "REPO_ACTIVITY=$days" >> $
          echo "::set-output name=days::$days"
  build:
    needs: check-if-there-are-commits
    runs-on: ubuntu-latest
    if: ${{ needs.check-if-there-are-commits.outputs.alive == 'true' }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
      - run: sudo npm i -g @adguard/hostlist-compiler

      - name: Checkout cache-domains
        uses: actions/checkout@v2
        with:
          repository: uklans/cache-domains
          path: .overlay/cache-domains

      - run: |
          cp cache-domains-config.json .overlay/cache-domains/scripts/config.json
          pushd .overlay/cache-domains/scripts/
          ./create-dnsmasq.sh
          popd
          cp -R .overlay/cache-domains/scripts/output/dnsmasq output/
          hostlist-compiler -c configuration.json -o adguard.txt

      - uses: EndBug/add-and-commit@v8 # You can change this to use a specific version.
        with:
          add: '*.txt'
          default_author: github_actions 
          message: 'generated'

